export const copy = {
  fr: {
    meta: {
      title: 'Mathieu Boucher — Développeur & designer',
      description:
        'Du développement web et des applications mobiles à l’imprimé et au numérique.',
    },
    nav: {
      home: 'Accueil',
      about: 'À propos',
      services: 'Services',
      print: 'Imprime',
      digital: 'Numérique',
      web: 'Web',
      apps: 'Applications',
      drone: 'Drone',
      estimate: 'Estimation',
      contact: 'Contact',
      blog: 'Blog',
      logo: 'Logo',
      portfolio: 'Portfolio',
      home2: 'Accueil 2',
      open: 'Ouvrir le menu',
      close: 'Fermer le menu',
      themeLight: 'Passer en mode clair',
      themeDark: 'Passer en mode sombre',
      langEn: 'Switch to English',
      langFr: 'Passer en français',
    },
    home: {
      name: 'Mathieu Boucher',
      role: 'Développeur & designer',
      intro:
        'Du développement web et des applications mobiles à l’imprimé et au numérique, je propose une gamme complète de services pour donner vie à vos projets et renforcer votre image, en ligne comme hors ligne.',
      ctaServices: 'Voir mes services',
      ctaContact: 'Contactez-moi',
      marquee:
        'MODERN LOOK • SCROLLING BANNER • S-SHAPE DESIGN • CHARCOAL & BLACK • CRUNCHY DESIGN TRENDS • UNIQUE WAVE • ',
      servicesEyebrow: 'Mes services',
      servicesLead:
        'Découvrez l’ensemble de mes services professionnels en développement web, design et solutions numériques adaptées à vos besoins.',
      servicesMore: 'En savoir plus',
      services: [
        {
          slug: 'applications',
          title: 'Application',
          text: 'Développement d’applications sur mesure pour iOS et Android. Des solutions mobiles innovantes pour votre entreprise.',
          cta: 'Application web',
        },
        {
          slug: 'web',
          title: 'Web',
          text: 'Création de sites web modernes et performants. Du design à l’intégration, je développe votre présence en ligne.',
          cta: 'Services web',
        },
        {
          slug: 'imprime',
          title: 'Imprimé',
          text: 'Design graphique et solutions d’impression professionnelles. De la conception à la production, je crée des supports visuels impactants.',
          cta: 'Services imprimé',
        },
        {
          slug: 'numerique',
          title: 'Numérique',
          text: 'Solutions numériques innovantes pour votre entreprise. Stratégie numérique, marketing automation et expérience utilisateur optimale.',
          cta: 'Services numériques',
        },
      ],
      projectsEyebrow: 'Derniers projets',
      projectsLead: 'Découvrez les derniers projets que j’ai réalisés pour mes clients.',
      projectsCta: 'Voir tous les projets',
      lightboxClose: 'Fermer',
      lightboxPrev: 'Projet précédent',
      lightboxNext: 'Projet suivant',
      projects: [
        'Projet 1',
        'Projet 2',
        'Projet 3',
        'Projet 4',
        'Projet 5',
        'Projet 6',
        'Projet 7',
        'Projet 8',
        'Projet 9',
      ],
      ctaTitle: 'Prêt à démarrer votre projet ?',
      ctaText:
        'Donnons vie à votre vision. Soumettez les détails de votre projet et je vous aiderai à créer quelque chose d’exceptionnel.',
      ctaButton: 'Soumettre votre projet',
      quotesEyebrow: 'Témoignages',
      quotesTitle: 'Ce que les gens disent de moi',
      quotesPrev: 'Témoignage précédent',
      quotesNext: 'Témoignage suivant',
      quotes: [
        {
          name: 'Jean Dupont',
          role: 'CEO, Tech Solutions',
          text: 'Mathieu a transformé notre présence en ligne avec un site web exceptionnel. Son expertise technique et sa créativité ont dépassé nos attentes.',
        },
        {
          name: 'Marie Lambert',
          role: 'Directrice Marketing, InnovCorp',
          text: 'Un professionnel talentueux qui comprend parfaitement les besoins de ses clients. Le résultat final était exactement ce que nous recherchions.',
        },
        {
          name: 'Pierre Martin',
          role: 'Fondateur, StartupX',
          text: 'Grâce à Mathieu, notre application a connu un succès immédiat. Son approche méthodique et sa créativité ont fait toute la différence.',
        },
        {
          name: 'Sophie Tremblay',
          role: 'Directrice Artistique, DesignLab',
          text: 'La collaboration avec Mathieu a été exceptionnelle. Son sens du design et sa capacité à traduire nos idées en réalité ont été déterminants pour notre succès.',
        },
        {
          name: 'Alexandre Roy',
          role: 'CTO, Numeric Innovations',
          text: 'Mathieu a développé une solution technique complexe qui a considérablement amélioré notre efficacité opérationnelle. Un vrai expert en développement.',
        },
        {
          name: 'Isabelle Bouchard',
          role: 'Propriétaire, Boutique Élégance',
          text: 'Notre boutique en ligne a connu une augmentation de 200% des ventes grâce au travail de Mathieu. Son expertise en e-commerce est remarquable.',
        },
        {
          name: 'Marc-André Gagnon',
          role: 'Directeur, Agence Marketing Plus',
          text: 'Mathieu a créé une plateforme marketing qui a révolutionné notre façon de travailler. Son approche innovante et sa maîtrise technique sont impressionnantes.',
        },
        {
          name: 'Julie Fortin',
          role: 'Fondatrice, ÉcoSolutions',
          text: 'Le site web développé par Mathieu reflète parfaitement notre engagement environnemental. Son attention aux détails et sa créativité sont exceptionnelles.',
        },
      ],
    },
    home2: {
      badge: 'Proposition de design',
      kicker: 'Développeur & designer',
      title: 'Web & apps.',
      titleAccent: 'Design & print.',
      lead:
        'Du web et des apps à l’imprimé et au numérique — une pratique pour donner vie à vos projets et renforcer votre image.',
      ctaPrimary: 'Voir les services',
      ctaSecondary: 'Me contacter',
      proof: 'Plus de 8 ans d’expérience — 25 entreprises accompagnées.',
      galleryEyebrow: 'Travail récent',
      pitchEyebrow: 'Une pratique complète',
      pitchTitle: 'De l’idée au livrable.',
      pitchLead:
        'Kickstart, affiner, livrer. React, design et imprimé — le même niveau d’exigence, en ligne comme hors ligne.',
      pillars: [
        {
          title: 'Créer',
          text: 'Sites, applications et identités pensés pour durer. Du pixel à l’architecture.',
        },
        {
          title: 'Affiner',
          text: 'Chaque détail compte. Je pousse jusqu’à ce que ça vous ressemble vraiment.',
        },
        {
          title: 'Livrer',
          text: 'Des projets qui marquent vos utilisateurs — et qui tiennent la route.',
        },
      ],
      servicesTitle: 'Quatre expertises, une direction.',
      quoteLabel: 'Témoignage',
      back: 'Voir l’accueil actuel',
      footerTitle: 'Travaillons ensemble',
      footerText: 'Pas de brief trop petit, pas d’attente. Un message, et on démarre.',
      footerCta: 'Lancer un projet',
      colServices: 'Services',
      colWork: 'Projets',
      colResources: 'Ressources',
      colStudio: 'Studio',
      colConnect: 'Connect',
      notice:
        'Les projets présentés sur ce site le sont à titre illustratif. Ils restent la propriété de leurs clients et créateurs. Logos et contenus de marque appartiennent à leurs détenteurs. Pour une mention différente ou un retrait, écrivez-moi.',
      newsTitle: 'Des nouvelles du studio, de temps en temps, dans votre boîte mail.',
      newsPlaceholder: 'Votre email',
      newsSubmit: 'S’inscrire',
      newsSuccess: 'Inscrit !',
      newsPending: 'Envoi...',
      newsLabel: 'Entrez votre email pour recevoir des nouvelles',
      newsError: 'Entrez une adresse email valide.',
    },
    about: {
      eyebrow: 'À propos',
      name: 'Mathieu Boucher',
      role: 'Développeur & designer',
      title: 'Qui suis-je?',
      values: 'Créativité – Passion – Authenticité',
      p1: 'Développeur & designer web freelance passionné, je cumule plus de 8 ans d’expérience en agence et en entreprise. Spécialisé en React et React Native, je crée des solutions web et mobiles sur mesure qui transforment vos idées en expériences digitales exceptionnelles.',
      p2: 'Entrepreneur dans l’âme, j’ai fondé ma propre agence à 20 ans et accompagné plus de 25 entreprises canadiennes vers le succès digital. Mon approche unique allie créativité, expertise technique et vision stratégique pour livrer des projets qui dépassent vos attentes et marquent durablement vos utilisateurs.',
    },
    services: {
      imprime: {
        eyebrow: 'Services',
        title: 'Imprime',
        titleAccent: 'Hors écran.',
        subtitle: 'Solutions d’impression professionnelles pour valoriser votre image',
        banner:
          'IMPRIMÉ • CARTES DE VISITE • FLYERS • AFFICHES • PACKAGING • SIGNALÉTIQUE • GRAND FORMAT • PAPETERIE • ',
        intro:
          'Je vous accompagne dans tous vos projets d’impression, de la conception à la réalisation. Cartes de visite, flyers, affiches, packaging et bien plus encore - je mets mon expertise au service de votre communication imprimée.',
        sectionTitle: 'Services d’Impression',
        sectionLead:
          'Des solutions d’impression sur mesure pour tous vos besoins de communication',
        groups: [
          {
            title: 'Supports de Communication',
            text: 'Je crée des supports imprimés qui renforcent votre identité de marque :',
            items: [
              'Cartes de visite professionnelles',
              'Flyers et dépliants publicitaires',
              'Affiches et bannières',
              'Brochures et catalogues',
              'Plaquettes commerciales',
              'En-têtes de lettres et factures',
            ],
          },
          {
            title: 'Packaging & Étiquetage',
            text: 'Je conçois des solutions d’emballage qui valorisent vos produits :',
            items: [
              'Étiquettes personnalisées',
              'Boîtes et emballages',
              'Sachets et pochettes',
              'Packaging écologique',
            ],
          },
          {
            title: 'Événementiel & Signalétique',
            text: 'Je réalise des supports pour vos événements et votre signalétique :',
            items: [
              'Roll-ups et kakémonos',
              'Signalétique intérieure et extérieure',
              'Supports d’exposition',
              'Badges et étiquettes nominatives',
            ],
          },
        ],
        listTitle: 'Liste de services',
        list: [
          'Cartes de visite',
          'Flyers et dépliants',
          'Affiches et bannières',
          'Brochures commerciales',
          'Catalogues produits',
          'Plaquettes d’entreprise',
          'En-têtes de lettres',
          'Étiquettes personnalisées',
          'Packaging sur mesure',
          'Boîtes et emballages',
          'Sachets et pochettes',
          'Roll-ups et kakémonos',
          'Signalétique',
          'Supports d’exposition',
          'Badges événementiels',
          'Calendriers',
          'Bloc-notes personnalisés',
          'Stickers et autocollants',
          'Papeterie commerciale',
          'Finitions spéciales',
          'Impression grand format',
        ],
        ctaTitle: 'Donnez vie à vos projets d’impression !',
        ctaText:
          'Discutons de vos besoins et créons ensemble des supports imprimés qui vous démarquent.',
      },
      numerique: {
        eyebrow: 'Services',
        title: 'Numérique',
        titleAccent: 'En image.',
        subtitle: 'Des solutions numériques innovantes pour propulser votre entreprise',
        banner:
          'NUMÉRIQUE • IDENTITÉ VISUELLE • MOTION DESIGN • RÉSEAUX SOCIAUX • STRATÉGIE DIGITALE • ILLUSTRATION • ',
        intro:
          'Je conçois des expériences numériques uniques, alignées sur vos besoins et vos valeurs. De la stratégie au design, en passant par l’automatisation marketing, je vous accompagne dans chaque étape de votre transformation numérique.',
        actions: ['Estimation', 'Contactez-moi'],
        sectionTitle: 'Services numériques',
        sectionLead: '',
        groups: [
          {
            title: 'Design & Identité visuelle',
            text: 'Je vous aide à poser une image forte et cohérente pour votre marque :',
            items: [
              'Création de logo',
              'Développement d’identité visuelle',
              'Templates personnalisés pour emails et blogs',
              'Visuels pour les réseaux sociaux',
              'Infographies & illustrations numériques',
              'Création d’icônes sur mesure',
            ],
          },
          {
            title: 'Design interactif & web',
            text: 'Je conçois des interfaces pensées pour l’utilisateur, intuitives et efficaces :',
            items: [
              'Design de sites web',
              'Design d’applications mobiles',
              'Présentations interactives',
              'Design UX/UI',
            ],
          },
          {
            title: 'Contenus visuels & médias',
            text: 'Je crée des visuels impactants pour soutenir vos communications :',
            items: [
              'Visuels pour événements, vidéos et podcasts',
              'Animation graphique (motion design)',
              'Contenus visuels pour vos articles de blog et réseaux',
            ],
          },
          {
            title: 'Accompagnement stratégique',
            text: 'Je vous accompagne pour bâtir une présence numérique cohérente et performante :',
            items: [
              'Audit et stratégie numérique',
              'Marketing automation (automatisation des campagnes)',
              'Accompagnement en crowdfunding',
              'Conseil en transformation digitale',
            ],
          },
        ],
        listTitle: 'Liste de services',
        list: [
          'Logo',
          'Identité visuelle',
          'Design de sites web',
          'Design réseaux sociaux',
          'Infographies',
          'Illustration numérique',
          'Templates pour emails',
          'Contenu visuel pour blogs',
          'Animation graphique',
          'Visuels pour événements',
          'Visuels pour podcasts',
          'Visuels pour vidéos',
          'Jeux vidéo',
          'Réalité augmentée/virtuelle',
          'Présentations interactives',
          'Crowdfunding',
          'Événements virtuels',
          'Webinaires',
          'Formations en ligne',
          'Design d’application',
          'Design d’icônes',
        ],
        ctaTitle: 'Transformer votre présence numérique !',
        ctaText:
          'Discutons de vos besoins et créons ensemble une stratégie numérique qui vous démarque.',
      },
      web: {
        eyebrow: 'Services',
        title: 'Web',
        titleAccent: 'En ligne.',
        subtitle: 'Développement web moderne et sur mesure pour votre présence en ligne',
        banner:
          'WEB • WORDPRESS • E-COMMERCE • REACT • SEO • SITES VITRINES • PERFORMANCE • MAINTENANCE • ',
        intro:
          'Je crée des sites web performants, responsives et optimisés qui reflètent votre identité de marque. De la conception à la mise en ligne, je vous accompagne dans tous les aspects de votre projet web.',
        sectionTitle: 'Services Web',
        sectionLead: 'Des solutions web complètes pour tous vos besoins numériques',
        groups: [
          {
            title: 'Sites Web & E-commerce',
            text: 'Je développe des sites web professionnels et des boutiques en ligne :',
            items: [
              'Sites WordPress personnalisés',
              'Boutiques WooCommerce et Shopify',
              'Sites avec Divi et Elementor',
              'Sites d’entreprise',
              'Portfolios et sites artistiques',
              'Landing pages optimisées',
            ],
          },
          {
            title: 'Design & Expérience Utilisateur',
            text: 'Je conçois des interfaces modernes et intuitives :',
            items: [
              'Design responsive (mobile-first)',
              'UX/UI design optimisé',
              'Interfaces utilisateur intuitives',
              'Design system cohérent',
            ],
          },
          {
            title: 'Maintenance & Optimisation',
            text: 'Je vous accompagne dans la maintenance et l’évolution de vos sites :',
            items: [
              'Maintenance et mises à jour',
              'Optimisation SEO et performance',
              'Sécurité et sauvegardes',
              'Formation et support technique',
            ],
          },
        ],
        listTitle: 'Liste de services',
        list: [
          'WordPress',
          'Divi',
          'Elementor',
          'WooCommerce',
          'Shopify',
          'React & Vue.js',
          'Sites vitrines',
          'E-commerce',
          'Sites d’entreprise',
          'Portfolios',
          'Landing pages',
          'Sites événementiels',
          'Design responsive',
          'UX/UI design',
          'PHP & MySQL',
          'Bases de données',
          'Optimisation SEO',
          'Performance web',
          'Sécurité',
          'Maintenance',
          'Mises à jour',
          'Support technique',
          'Formation',
          'Hébergement',
        ],
        ctaTitle: 'Créez votre présence web de demain !',
        ctaText: 'Discutons de votre projet web et créons ensemble un site qui vous démarque.',
      },
      applications: {
        eyebrow: 'Services',
        title: 'Applications',
        titleAccent: 'Sur mesure.',
        subtitle: 'Applications React et React Native modernes sur mesure',
        banner:
          'APPLICATIONS • REACT • REACT NATIVE • ANDROID • NEXT.JS • TYPESCRIPT • API • ',
        intro:
          'Je développe des applications React et React Native performantes qui transforment vos idées en expériences utilisateur exceptionnelles. De la conception à la publication, je vous accompagne dans tous les aspects de votre projet d’application.',
        sectionTitle: 'Services d’Applications',
        sectionLead: 'Des solutions d’applications complètes pour tous vos besoins numériques',
        groups: [
          {
            title: 'Applications React',
            text: 'Je développe des applications React modernes et performantes :',
            items: [
              'Applications web React personnalisées',
              'Single Page Applications (SPA)',
              'Applications React Native',
              'Interfaces utilisateur interactives',
              'Intégration API et services',
              'Optimisation des performances',
            ],
          },
          {
            title: 'Applications React Native',
            text: 'Je développe des applications React Native cross-platform :',
            items: [
              'Applications React Native iOS et Android',
              'Interfaces utilisateur natives',
              'Intégration avec les APIs mobiles',
              'Optimisation des performances mobiles',
            ],
          },
          {
            title: 'Technologies & Frameworks',
            text: 'J’utilise les technologies les plus récentes pour des applications performantes :',
            items: [
              'React, React Native, Next.js',
              'JavaScript ES6+, TypeScript',
              'Node.js et Express',
              'Bases de données (MongoDB, PostgreSQL)',
              'APIs REST et GraphQL',
              'Déploiement et CI/CD',
            ],
          },
          {
            title: 'Maintenance & Évolution',
            text: 'Je vous accompagne dans la maintenance et l’évolution de vos applications :',
            items: [
              'Maintenance et mises à jour',
              'Optimisation des performances',
              'Sécurité et tests',
              'Formation et support technique',
            ],
          },
        ],
        listTitle: 'Liste de services',
        list: [
          'React',
          'React Native',
          'Next.js',
          'TypeScript',
          'Applications web',
          'Android',
          'Interfaces natives',
          'Single Page Apps',
          'Interfaces interactives',
          'Node.js',
          'Express',
          'MongoDB',
          'PostgreSQL',
          'API REST',
          'GraphQL',
          'Tests automatisés',
          'CI/CD',
          'Déploiement',
          'Performance',
          'Sécurité',
          'Maintenance',
        ],
        ctaTitle: 'Transformez vos idées en applications !',
        ctaText:
          'Discutons de votre projet d’application et créons ensemble une solution qui vous démarque.',
      },
      drone: {
        eyebrow: 'Services',
        title: 'Drone',
        titleAccent: 'En vol.',
        subtitle: 'Services de photographie et vidéographie aériennes professionnelles',
        banner:
          'DRONE • PHOTO AÉRIENNE • VIDÉO AÉRIENNE • INSPECTION • CARTOGRAPHIE 3D • IMMOBILIER • ',
        intro:
          'Je propose des services de drone professionnels pour capturer vos projets sous un angle unique. Photographie aérienne, vidéographie, inspection et cartographie - je mets la technologie drone au service de vos besoins.',
        sectionTitle: 'Services Drone',
        sectionLead:
          'Des solutions aériennes complètes pour tous vos besoins en imagerie et inspection',
        groups: [
          {
            title: 'Photographie Aérienne',
            text: 'Je capture des images aériennes exceptionnelles pour valoriser vos projets :',
            items: [
              'Photographie immobilière',
              'Photographie événementielle',
              'Photographie de paysages',
              'Photographie architecturale',
              'Photographie commerciale',
              'Photographie pour réseaux sociaux',
            ],
          },
          {
            title: 'Vidéographie Aérienne',
            text: 'Je réalise des vidéos aériennes cinématiques et professionnelles :',
            items: [
              'Vidéos promotionnelles',
              'Vidéos immobilières',
              'Vidéos événementielles',
              'Vidéos publicitaires',
              'Contenu pour réseaux sociaux',
            ],
          },
          {
            title: 'Inspection & Cartographie',
            text: 'J’utilise la technologie drone pour des inspections précises et sécurisées :',
            items: [
              'Inspection de toits et structures',
              'Inspection industrielle',
              'Suivi de chantiers',
              'Surveillance de sites',
              'Thermographie',
            ],
          },
          {
            title: 'Cartographie 3D & Modélisation',
            text: 'Je crée des modèles 3D précis et des cartographies détaillées :',
            items: [
              'Cartographie 3D',
              'Modélisation 3D',
              'Orthophotos',
              'Levés topographiques',
            ],
          },
        ],
        listTitle: 'Liste de services',
        list: [
          'Photographie aérienne',
          'Vidéographie aérienne',
          'Vidéos promotionnelles',
          'Vidéos immobilières',
          'Vidéos événementielles',
          'Vidéos publicitaires',
          'Inspection de toits',
          'Inspection de structures',
          'Inspection industrielle',
          'Cartographie 3D',
          'Modélisation 3D',
          'Orthophotos',
          'Levés topographiques',
          'Suivi de chantiers',
          'Photogrammétrie',
          'Thermographie',
          'Agriculture de précision',
          'Surveillance de sites',
          'Couverture événements',
          'Contenu pour réseaux sociaux',
          'Post-production vidéo',
          'Colorisation et étalonnage',
        ],
        ctaTitle: 'Capturez vos projets sous un nouvel angle !',
        ctaText:
          'Discutons de vos besoins et créons ensemble des contenus aériens qui vous démarquent.',
      },
    },
    contact: {
      eyebrow: 'Contact',
      title: 'Contact',
      addressLabel: 'Adresse',
      address: '1041 4e rue Croteau, St-Valère, QC',
      postal: 'G0P 1M0',
      phoneLabel: 'Téléphone',
      phone: '+1 (819) 302-8781',
      emailLabel: 'Email',
      email: 'mrboucher95@gmail.com',
      formTitle: 'Formulaire de contact',
      name: 'Votre nom',
      namePh: 'Entrez votre nom complet',
      emailField: 'Votre email',
      emailPh: 'Entrez votre adresse email',
      subject: 'Sujet',
      subjectPh: 'Quel est le sujet de votre message?',
      message: 'Votre message',
      messagePh: 'Écrivez votre message ici...',
      prev: 'Précédent',
      next: 'Suivant',
      send: 'Envoyer',
      sent: 'Merci. Votre message est prêt — je vous répondrai rapidement.',
    },
    estimate: {
      title: 'Estimateur de projet',
      lead: 'Répondez à quelques questions pour obtenir une estimation indicative de votre projet.',
      which: 'Quel service vous intéresse?',
      from: 'À partir de',
      included: 'Inclus',
      step: 'Étape',
      selectAll: 'Sélectionnez toutes les options qui s’appliquent.',
      prev: 'Précédent',
      next: 'Suivant',
      see: 'Voir l’estimation',
      yours: 'Votre estimation',
      total: 'Total estimé',
      disclaimer:
        'Cette estimation est indicative et peut varier selon la complexité réelle du projet. Un devis détaillé sera fourni après discussion.',
      discuss: 'Discuter de mon projet',
      again: 'Nouvelle estimation',
    },
    footer: '© 2026 m-boucher. Tous droits réservés.',
    blog: {
      eyebrow: 'Blog',
      title: 'Le blog',
      lead: 'Guides pratiques sur le logo, l’identité visuelle, le design web et l’intégration — pour les entreprises et startups qui veulent une image claire, en ligne comme hors ligne.',
      read: 'Lire l’article',
      imageSlot: 'Image',
      back: 'Tous les articles',
      prev: 'Article précédent',
      next: 'Article suivant',
      pager: 'Autres articles',
      faq: 'Questions fréquentes',
      ctaTitle: 'Un projet en tête ?',
      ctaText: 'Logo, site, identité : parlons de ce dont vous avez besoin.',
      metaTitle: 'Blog — design, web et marque | Mathieu Boucher',
      metaDescription:
        'Articles sur le logo vectoriel, l’identité visuelle, le design web et l’intégration. Conseils concrets pour entreprises et startups au Québec.',
    },
    portfolio: {
      eyebrow: 'Portfolio',
      title: 'Les projets',
      lead: 'Une sélection de travaux en design, web et identité — les mêmes pièces que sur l’accueil, et d’autres à venir.',
      metaTitle: 'Portfolio — Mathieu Boucher',
      metaDescription:
        'Portfolio de Mathieu Boucher : sites, identité visuelle et projets numériques pour entreprises au Québec.',
      ctaTitle: 'Un projet en tête ?',
      ctaText: 'Parlons de ce dont vous avez besoin. Logo, site, identité.',
    },
    logo: {
      metaTitle: 'Logo — Mathieu Boucher',
      title: 'Logo',
      lead: 'Le logo est le symbole le plus immédiatement reconnaissable de la marque.',
      systemEyebrow: 'Système',
      systemTitle: 'Le monogramme a une expression — la vague en S.',
      systemText:
        'Deux vagues s’emboîtent pour former le signe MB. Le geste est le même à l’écran et sur papier : un mouvement, pas un pictogramme figé.',
      versionEyebrow: 'Le signe',
      versionTitle: 'Construit, pas décoré',
      versionText:
        'Le monogramme tient dans un cadre de construction. Il a besoin d’air, de proportion, et d’un fond assez sombre pour que le blanc porte.',
      useEyebrow: 'Usage',
      useTitle: 'Charcoal & black',
      useText:
        'Blanc sur charcoal. Jamais étiré, jamais recadré, jamais recoloré hors de la palette. Sur fond clair, le signe passe en charcoal — pas en gris.',
      rules: [
        'Garder les proportions du fichier source.',
        'Laisser un dégagement au moins égal à la hauteur d’une vague.',
        'Ne pas ajouter d’ombre, de contour ou d’effet.',
      ],
    },
    notFound: {
      code: '404',
      title: 'Page non trouvée',
      text: 'La page que vous recherchez n’existe pas.',
      back: 'Retour à l’accueil',
    },
  },
  en: {
    meta: {
      title: 'Mathieu Boucher — Developer & designer',
      description:
        'From web development and mobile apps to print and digital solutions.',
    },
    nav: {
      home: 'Home',
      about: 'About',
      services: 'Services',
      print: 'Print',
      digital: 'Numeric',
      web: 'Web',
      apps: 'Applications',
      drone: 'Drone',
      estimate: 'Estimate',
      contact: 'Contact',
      blog: 'Blog',
      logo: 'Logo',
      portfolio: 'Portfolio',
      home2: 'Home 2',
      open: 'Open menu',
      close: 'Close menu',
      themeLight: 'Switch to light mode',
      themeDark: 'Switch to dark mode',
      langEn: 'Switch to English',
      langFr: 'Switch to French',
    },
    home: {
      name: 'Mathieu Boucher',
      role: 'Freelance Web Developer & Designer',
      intro:
        'From web development and mobile applications to print and digital solutions — I offer a complete range of services to bring your projects to life and strengthen your brand, online and offline.',
      ctaServices: 'View my services',
      ctaContact: 'Contact me',
      marquee:
        'MODERN LOOK • SCROLLING BANNER • S-SHAPE DESIGN • CHARCOAL & BLACK • CRUNCHY DESIGN TRENDS • UNIQUE WAVE • ',
      servicesEyebrow: 'My Services',
      servicesLead:
        'Discover all my professional services in web development, design and numeric solutions adapted to your needs.',
      servicesMore: 'Learn More',
      services: [
        {
          slug: 'applications',
          title: 'Application',
          text: 'Custom application development for iOS and Android. Innovative mobile solutions for your business.',
          cta: 'Web Application',
        },
        {
          slug: 'web',
          title: 'Web',
          text: 'Creation of modern and high-performance websites. From design to integration, I develop your online presence.',
          cta: 'Web Services',
        },
        {
          slug: 'imprime',
          title: 'Print',
          text: 'Graphic design and professional printing solutions. From conception to production, I create impactful visual materials.',
          cta: 'Print Services',
        },
        {
          slug: 'numerique',
          title: 'Numeric',
          text: 'Innovative numeric solutions for your business. Numeric strategy, marketing automation and optimal user experience.',
          cta: 'Numeric Services',
        },
      ],
      projectsEyebrow: 'Latest Projects',
      projectsLead: 'Discover the latest projects I have completed for my clients.',
      projectsCta: 'View All Projects',
      lightboxClose: 'Close',
      lightboxPrev: 'Previous project',
      lightboxNext: 'Next project',
      projects: [
        'Project 1',
        'Project 2',
        'Project 3',
        'Project 4',
        'Project 5',
        'Project 6',
        'Project 7',
        'Project 8',
        'Project 9',
      ],
      ctaTitle: 'Ready to Start Your Project?',
      ctaText:
        'Let’s bring your vision to life. Submit your project details and I’ll help you create something amazing.',
      ctaButton: 'Submit Your Project',
      quotesEyebrow: 'Testimonials',
      quotesTitle: 'What People Say About Me',
      quotesPrev: 'Previous testimonial',
      quotesNext: 'Next testimonial',
      quotes: [
        {
          name: 'Jean Dupont',
          role: 'CEO, Tech Solutions',
          text: 'Mathieu transformed our online presence with an exceptional website. His technical expertise and creativity exceeded our expectations.',
        },
        {
          name: 'Marie Lambert',
          role: 'Marketing Director, InnovCorp',
          text: 'A talented professional who truly understands his clients’ needs. The final result was exactly what we were looking for.',
        },
        {
          name: 'Pierre Martin',
          role: 'Founder, StartupX',
          text: 'Thanks to Mathieu, our app was an immediate success. His methodical approach and creativity made all the difference.',
        },
        {
          name: 'Sophie Tremblay',
          role: 'Art Director, DesignLab',
          text: 'Working with Mathieu was exceptional. His design sense and ability to turn ideas into reality were decisive for our success.',
        },
        {
          name: 'Alexandre Roy',
          role: 'CTO, Numeric Innovations',
          text: 'Mathieu built a complex technical solution that significantly improved our operational efficiency. A true development expert.',
        },
        {
          name: 'Isabelle Bouchard',
          role: 'Owner, Boutique Élégance',
          text: 'Our online store saw a 200% increase in sales thanks to Mathieu’s work. His e-commerce expertise is remarkable.',
        },
        {
          name: 'Marc-André Gagnon',
          role: 'Director, Agence Marketing Plus',
          text: 'Mathieu created a marketing platform that changed how we work. His innovative approach and technical mastery are impressive.',
        },
        {
          name: 'Julie Fortin',
          role: 'Founder, ÉcoSolutions',
          text: 'The website Mathieu developed perfectly reflects our environmental commitment. His attention to detail and creativity are exceptional.',
        },
      ],
    },
    home2: {
      badge: 'Design proposal',
      kicker: 'Developer & designer',
      title: 'Web & apps.',
      titleAccent: 'Design & print.',
      lead:
        'From web and apps to print and digital — one practice to bring your projects to life and strengthen your brand.',
      ctaPrimary: 'See services',
      ctaSecondary: 'Contact me',
      proof: '8 years of experience — 25 companies shipped with.',
      galleryEyebrow: 'Recent work',
      pitchEyebrow: 'A complete practice',
      pitchTitle: 'From idea to delivery.',
      pitchLead:
        'Kickstart, refine, ship. React, design and print — the same standard, online and off.',
      pillars: [
        {
          title: 'Create',
          text: 'Sites, apps and identities built to last. From the pixel to the architecture.',
        },
        {
          title: 'Refine',
          text: 'Every detail counts. I push until it actually feels like you.',
        },
        {
          title: 'Deliver',
          text: 'Work that stays with your users — and holds up in production.',
        },
      ],
      servicesTitle: 'Four crafts, one direction.',
      quoteLabel: 'Testimonial',
      back: 'See the current home',
      footerTitle: 'Let’s work together',
      footerText: 'No brief too small, no waiting. Send a note and we start.',
      footerCta: 'Start a project',
      colServices: 'Services',
      colWork: 'Work',
      colResources: 'Resources',
      colStudio: 'Studio',
      colConnect: 'Connect',
      notice:
        'Featured work on this site is shown for illustration. Projects remain the property of their clients and makers. Logos and branded content belong to their owners. For a different credit or a takedown, get in touch.',
      newsTitle: 'Studio notes, once in a while, in your inbox.',
      newsPlaceholder: 'Your email',
      newsSubmit: 'Subscribe',
      newsSuccess: 'Subscribed!',
      newsPending: 'Sending...',
      newsLabel: 'Enter your email to subscribe',
      newsError: 'Enter a valid email address.',
    },
    about: {
      eyebrow: 'About',
      name: 'Mathieu Boucher',
      role: 'Developer & designer',
      title: 'Who am I?',
      values: 'Creativity – Passion – Authenticity',
      p1: 'Passionate freelance web developer & designer with over 8 years of experience in agencies and companies. Specialized in React and React Native, I create custom web and mobile solutions that transform your ideas into exceptional digital experiences.',
      p2: 'Entrepreneur at heart, I founded my own agency at 20 and guided over 25 Canadian companies to digital success. My unique approach combines creativity, technical expertise, and strategic vision to deliver projects that exceed expectations and leave a lasting mark on your users.',
    },
    services: {
      imprime: {
        eyebrow: 'Services',
        title: 'Print',
        titleAccent: 'Off screen.',
        subtitle: 'Professional print solutions to elevate your image',
        banner:
          'PRINT • BUSINESS CARDS • FLYERS • POSTERS • PACKAGING • SIGNAGE • LARGE FORMAT • STATIONERY • ',
        intro:
          'I support you through every print project, from concept to production. Business cards, flyers, posters, packaging and more — I put my expertise at the service of your printed communication.',
        sectionTitle: 'Print Services',
        sectionLead: 'Custom print solutions for all your communication needs',
        groups: [
          {
            title: 'Communication Materials',
            text: 'I create printed materials that strengthen your brand identity:',
            items: [
              'Professional business cards',
              'Advertising flyers and leaflets',
              'Posters and banners',
              'Brochures and catalogs',
              'Sales sheets',
              'Letterheads and invoices',
            ],
          },
          {
            title: 'Packaging & Labeling',
            text: 'I design packaging that showcases your products:',
            items: [
              'Custom labels',
              'Boxes and packaging',
              'Pouches and sleeves',
              'Eco-friendly packaging',
            ],
          },
          {
            title: 'Events & Signage',
            text: 'I produce materials for your events and wayfinding:',
            items: [
              'Roll-ups and banners',
              'Indoor and outdoor signage',
              'Exhibition materials',
              'Name badges and labels',
            ],
          },
        ],
        listTitle: 'Service list',
        list: [
          'Business cards',
          'Flyers and leaflets',
          'Posters and banners',
          'Commercial brochures',
          'Product catalogs',
          'Company sheets',
          'Letterheads',
          'Custom labels',
          'Custom packaging',
          'Boxes and packaging',
          'Pouches and sleeves',
          'Roll-ups',
          'Signage',
          'Exhibition materials',
          'Event badges',
          'Calendars',
          'Custom notepads',
          'Stickers',
          'Business stationery',
          'Special finishes',
          'Large-format printing',
        ],
        ctaTitle: 'Bring your print projects to life!',
        ctaText: 'Let’s discuss your needs and create printed materials that set you apart.',
      },
      numerique: {
        eyebrow: 'Services',
        title: 'Numeric',
        titleAccent: 'In image.',
        subtitle: 'Innovative digital solutions to propel your business',
        banner:
          'DIGITAL • VISUAL IDENTITY • MOTION DESIGN • SOCIAL MEDIA • DIGITAL STRATEGY • ILLUSTRATION • ',
        intro:
          'I design unique digital experiences aligned with your needs and values. From strategy to design and marketing automation, I support every step of your digital transformation.',
        actions: ['Estimate', 'Contact me'],
        sectionTitle: 'Numeric services',
        sectionLead: '',
        groups: [
          {
            title: 'Design & visual identity',
            text: 'I help you build a strong, coherent brand image:',
            items: [
              'Logo creation',
              'Visual identity development',
              'Custom email and blog templates',
              'Social media visuals',
              'Infographics & digital illustration',
              'Custom icon design',
            ],
          },
          {
            title: 'Interactive & web design',
            text: 'I design interfaces that are intuitive and effective:',
            items: [
              'Website design',
              'Mobile app design',
              'Interactive presentations',
              'UX/UI design',
            ],
          },
          {
            title: 'Visual content & media',
            text: 'I create impactful visuals for your communications:',
            items: [
              'Visuals for events, videos and podcasts',
              'Motion design',
              'Visual content for blogs and social',
            ],
          },
          {
            title: 'Strategic support',
            text: 'I help you build a coherent, high-performing digital presence:',
            items: [
              'Digital audit and strategy',
              'Marketing automation',
              'Crowdfunding support',
              'Digital transformation consulting',
            ],
          },
        ],
        listTitle: 'Service list',
        list: [
          'Logo',
          'Visual identity',
          'Website design',
          'Social media design',
          'Infographics',
          'Digital illustration',
          'Email templates',
          'Blog visuals',
          'Motion graphics',
          'Event visuals',
          'Podcast visuals',
          'Video visuals',
          'Video games',
          'AR/VR',
          'Interactive presentations',
          'Crowdfunding',
          'Virtual events',
          'Webinars',
          'Online training',
          'App design',
          'Icon design',
        ],
        ctaTitle: 'Transform your digital presence!',
        ctaText: 'Let’s discuss your needs and create a digital strategy that sets you apart.',
      },
      web: {
        eyebrow: 'Services',
        title: 'Web',
        titleAccent: 'Online.',
        subtitle: 'Modern, custom web development for your online presence',
        banner:
          'WEB • WORDPRESS • E-COMMERCE • REACT • SEO • LANDING PAGES • PERFORMANCE • MAINTENANCE • ',
        intro:
          'I build fast, responsive, optimized websites that reflect your brand. From concept to launch, I support every part of your web project.',
        sectionTitle: 'Web Services',
        sectionLead: 'Complete web solutions for all your digital needs',
        groups: [
          {
            title: 'Websites & E-commerce',
            text: 'I develop professional websites and online stores:',
            items: [
              'Custom WordPress sites',
              'WooCommerce and Shopify stores',
              'Divi and Elementor sites',
              'Corporate websites',
              'Portfolios and artist sites',
              'Optimized landing pages',
            ],
          },
          {
            title: 'Design & User Experience',
            text: 'I design modern, intuitive interfaces:',
            items: [
              'Responsive design (mobile-first)',
              'Optimized UX/UI design',
              'Intuitive user interfaces',
              'Coherent design systems',
            ],
          },
          {
            title: 'Maintenance & Optimization',
            text: 'I support the maintenance and evolution of your sites:',
            items: [
              'Maintenance and updates',
              'SEO and performance optimization',
              'Security and backups',
              'Training and technical support',
            ],
          },
        ],
        listTitle: 'Service list',
        list: [
          'WordPress',
          'Divi',
          'Elementor',
          'WooCommerce',
          'Shopify',
          'React & Vue.js',
          'Showcase sites',
          'E-commerce',
          'Corporate sites',
          'Portfolios',
          'Landing pages',
          'Event sites',
          'Responsive design',
          'UX/UI design',
          'PHP & MySQL',
          'Databases',
          'SEO optimization',
          'Web performance',
          'Security',
          'Maintenance',
          'Updates',
          'Technical support',
          'Training',
          'Hosting',
        ],
        ctaTitle: 'Build tomorrow’s web presence!',
        ctaText: 'Let’s discuss your web project and create a site that sets you apart.',
      },
      applications: {
        eyebrow: 'Services',
        title: 'Applications',
        titleAccent: 'Custom-built.',
        subtitle: 'Modern custom React and React Native apps',
        banner:
          'APPS • REACT • REACT NATIVE • ANDROID • NEXT.JS • TYPESCRIPT • API • ',
        intro:
          'I build high-performance React and React Native apps that turn your ideas into exceptional user experiences. From concept to launch, I support every part of your app project.',
        sectionTitle: 'Application Services',
        sectionLead: 'Complete application solutions for all your digital needs',
        groups: [
          {
            title: 'React Applications',
            text: 'I develop modern, high-performance React apps:',
            items: [
              'Custom React web apps',
              'Single Page Applications (SPA)',
              'React Native apps',
              'Interactive user interfaces',
              'API and service integration',
              'Performance optimization',
            ],
          },
          {
            title: 'React Native Applications',
            text: 'I develop cross-platform React Native apps:',
            items: [
              'React Native iOS and Android apps',
              'Native user interfaces',
              'Mobile API integration',
              'Mobile performance optimization',
            ],
          },
          {
            title: 'Technologies & Frameworks',
            text: 'I use current technologies for performant applications:',
            items: [
              'React, React Native, Next.js',
              'JavaScript ES6+, TypeScript',
              'Node.js and Express',
              'Databases (MongoDB, PostgreSQL)',
              'REST and GraphQL APIs',
              'Deployment and CI/CD',
            ],
          },
          {
            title: 'Maintenance & Evolution',
            text: 'I support the maintenance and evolution of your apps:',
            items: [
              'Maintenance and updates',
              'Performance optimization',
              'Security and testing',
              'Training and technical support',
            ],
          },
        ],
        listTitle: 'Service list',
        list: [
          'React',
          'React Native',
          'Next.js',
          'TypeScript',
          'Web apps',
          'Android',
          'Native interfaces',
          'Single Page Apps',
          'Interactive interfaces',
          'Node.js',
          'Express',
          'MongoDB',
          'PostgreSQL',
          'REST API',
          'GraphQL',
          'Automated tests',
          'CI/CD',
          'Deployment',
          'Performance',
          'Security',
          'Maintenance',
        ],
        ctaTitle: 'Turn your ideas into apps!',
        ctaText: 'Let’s discuss your app project and create a solution that sets you apart.',
      },
      drone: {
        eyebrow: 'Services',
        title: 'Drone',
        titleAccent: 'In flight.',
        subtitle: 'Professional aerial photography and videography services',
        banner:
          'DRONE • AERIAL PHOTO • AERIAL VIDEO • INSPECTION • 3D MAPPING • REAL ESTATE • ',
        intro:
          'I offer professional drone services to capture your projects from a unique angle. Aerial photography, videography, inspection and mapping — I put drone technology at the service of your needs.',
        sectionTitle: 'Drone Services',
        sectionLead: 'Complete aerial solutions for all your imaging and inspection needs',
        groups: [
          {
            title: 'Aerial Photography',
            text: 'I capture exceptional aerial images to showcase your projects:',
            items: [
              'Real estate photography',
              'Event photography',
              'Landscape photography',
              'Architectural photography',
              'Commercial photography',
              'Social media photography',
            ],
          },
          {
            title: 'Aerial Videography',
            text: 'I create cinematic and professional aerial videos:',
            items: [
              'Promotional videos',
              'Real estate videos',
              'Event videos',
              'Commercial videos',
              'Social media content',
            ],
          },
          {
            title: 'Inspection & Mapping',
            text: 'I use drone technology for precise and safe inspections:',
            items: [
              'Roof and structure inspection',
              'Industrial inspection',
              'Construction site monitoring',
              'Site surveillance',
              'Thermography',
            ],
          },
          {
            title: '3D Mapping & Modeling',
            text: 'I create precise 3D models and detailed mappings:',
            items: [
              '3D mapping',
              '3D modeling',
              'Orthophotos',
              'Topographic surveys',
            ],
          },
        ],
        listTitle: 'Service list',
        list: [
          'Aerial photography',
          'Aerial videography',
          'Promotional videos',
          'Real estate videos',
          'Event videos',
          'Commercial videos',
          'Roof inspection',
          'Structure inspection',
          'Industrial inspection',
          '3D mapping',
          '3D modeling',
          'Orthophotos',
          'Topographic surveys',
          'Site monitoring',
          'Photogrammetry',
          'Thermography',
          'Precision agriculture',
          'Site surveillance',
          'Event coverage',
          'Social media content',
          'Video post-production',
          'Color grading',
        ],
        ctaTitle: 'Capture your projects from a new angle!',
        ctaText: 'Let’s discuss your needs and create aerial content that sets you apart.',
      },
    },
    contact: {
      eyebrow: 'Contact',
      title: 'Contact',
      addressLabel: 'Address',
      address: '1041 4e rue Croteau, St-Valère, QC',
      postal: 'G0P 1M0',
      phoneLabel: 'Phone',
      phone: '+1 (819) 302-8781',
      emailLabel: 'Email',
      email: 'mrboucher95@gmail.com',
      formTitle: 'Contact form',
      name: 'Your name',
      namePh: 'Enter your full name',
      emailField: 'Your email',
      emailPh: 'Enter your email address',
      subject: 'Subject',
      subjectPh: 'What is the subject of your message?',
      message: 'Your message',
      messagePh: 'Write your message here...',
      prev: 'Previous',
      next: 'Next',
      send: 'Send',
      sent: 'Thank you. Your message is ready — I will get back to you shortly.',
    },
    estimate: {
      title: 'Project estimator',
      lead: 'Answer a few questions to get an indicative estimate for your project.',
      which: 'Which service are you interested in?',
      from: 'From',
      included: 'Included',
      step: 'Step',
      selectAll: 'Select all options that apply.',
      prev: 'Previous',
      next: 'Next',
      see: 'See estimate',
      yours: 'Your estimate',
      total: 'Estimated total',
      disclaimer:
        'This estimate is indicative and may vary based on actual project complexity. A detailed quote will be provided after discussion.',
      discuss: 'Discuss my project',
      again: 'New estimate',
    },
    footer: '© 2026 m-boucher. All Rights Reserved.',
    blog: {
      eyebrow: 'Blog',
      title: 'The blog',
      lead: 'Practical guides on logos, visual identity, web design and front-end — for businesses and startups that want a clear image, online and off.',
      read: 'Read the article',
      imageSlot: 'Image',
      back: 'All articles',
      prev: 'Previous article',
      next: 'Next article',
      pager: 'More articles',
      faq: 'Frequently asked questions',
      ctaTitle: 'A project in mind?',
      ctaText: 'Logo, site, identity: let’s talk about what you need.',
      metaTitle: 'Blog — design, web and brand | Mathieu Boucher',
      metaDescription:
        'Articles on vector logos, visual identity, web design and front-end. Practical notes for businesses and startups in Quebec.',
    },
    portfolio: {
      eyebrow: 'Portfolio',
      title: 'The work',
      lead: 'A selection of design, web and identity pieces — the same set as on the home page, with more to come.',
      metaTitle: 'Portfolio — Mathieu Boucher',
      metaDescription:
        'Portfolio of Mathieu Boucher: websites, visual identity and digital work for businesses in Quebec.',
      ctaTitle: 'A project in mind?',
      ctaText: 'Let’s talk about what you need. Logo, site, identity.',
    },
    logo: {
      metaTitle: 'Logo — Mathieu Boucher',
      title: 'Logo',
      lead: 'The logo is the most instantly recognizable symbol of the brand.',
      systemEyebrow: 'System',
      systemTitle: 'The monogram has one expression — the S-wave.',
      systemText:
        'Two waves lock together to form the MB mark. The gesture is the same on screen and on paper: motion, not a frozen pictogram.',
      versionEyebrow: 'The mark',
      versionTitle: 'Built, not decorated',
      versionText:
        'The monogram lives inside a construction frame. It needs air, proportion, and a dark enough ground for the white to carry.',
      useEyebrow: 'Usage',
      useTitle: 'Charcoal & black',
      useText:
        'White on charcoal. Never stretched, cropped, or recolored outside the palette. On a light ground, the mark flips to charcoal — never gray.',
      rules: [
        'Keep the source file proportions.',
        'Leave clearance at least equal to the height of one wave.',
        'Do not add a drop shadow, outline, or effect.',
      ],
    },
    notFound: {
      code: '404',
      title: 'Page Not Found',
      text: 'The page you are looking for does not exist.',
      back: 'Back to Home',
    },
  },
}

export const estimatorConfig = {
  print: {
    labelKey: 'print',
    from: 800,
    questions: [
      {
        id: 'type',
        multi: false,
        title: { fr: 'Type de projet', en: 'Project type' },
        options: [
          { id: 'logo', label: { fr: 'Logo', en: 'Logo' }, price: 800 },
          {
            id: 'brand',
            label: { fr: 'Image de marque complète', en: 'Full branding' },
            price: 2500,
          },
          {
            id: 'pack',
            label: { fr: 'Pack imprimé (cartes, dépliants…)', en: 'Print pack (cards, brochures…)' },
            price: 1200,
          },
          {
            id: 'sign',
            label: { fr: 'Signalisation / affichage', en: 'Signage / display' },
            price: 900,
          },
        ],
      },
      {
        id: 'extras',
        multi: true,
        title: { fr: 'Livrables additionnels', en: 'Additional deliverables' },
        options: [
          { id: 'cards', label: { fr: 'Cartes d’affaires (50 cartes)', en: 'Business cards (50 cards)' }, price: 80 },
          { id: 'brochure', label: { fr: 'Brochure / dépliant (100 exemplaires)', en: 'Brochure / flyer (100 copies)' }, price: 150 },
          { id: 'poster', label: { fr: 'Affiche (25 exemplaires)', en: 'Poster (25 copies)' }, price: 120 },
          { id: 'packaging', label: { fr: 'Emballage (1 concept)', en: 'Packaging (1 concept)' }, price: 400 },
        ],
      },
      {
        id: 'revisions',
        multi: false,
        title: { fr: 'Rondes de révisions', en: 'Revision rounds' },
        options: [
          { id: 'r2', label: { fr: '2 rondes (inclus)', en: '2 rounds (included)' }, price: 0, included: true },
          { id: 'r4', label: { fr: '4 rondes', en: '4 rounds' }, price: 200 },
          { id: 'unlimited', label: { fr: 'Révisions illimitées', en: 'Unlimited revisions' }, price: 500 },
        ],
      },
    ],
  },
  digital: {
    labelKey: 'digital',
    from: 600,
    questions: [
      {
        id: 'scope',
        multi: false,
        title: { fr: 'Portée du projet', en: 'Project scope' },
        options: [
          { id: 'social', label: { fr: 'Réseaux sociaux', en: 'Social media' }, price: 600 },
          { id: 'ads', label: { fr: 'Campagne publicitaire', en: 'Advertising campaign' }, price: 1500 },
          { id: 'strategy', label: { fr: 'Stratégie numérique complète', en: 'Full digital strategy' }, price: 3500 },
        ],
      },
      {
        id: 'platforms',
        multi: true,
        title: { fr: 'Plateformes', en: 'Platforms' },
        options: [
          { id: 'meta', label: { fr: 'Facebook / Instagram', en: 'Facebook / Instagram' }, price: 200 },
          { id: 'linkedin', label: { fr: 'LinkedIn', en: 'LinkedIn' }, price: 200 },
          { id: 'google', label: { fr: 'Google Ads', en: 'Google Ads' }, price: 250 },
          { id: 'email', label: { fr: 'Infolettre / email', en: 'Newsletter / email' }, price: 180 },
        ],
      },
      {
        id: 'duration',
        multi: false,
        title: { fr: 'Durée d’accompagnement', en: 'Support duration' },
        options: [
          { id: 'm1', label: { fr: '1 mois', en: '1 month' }, price: 800 },
          { id: 'm3', label: { fr: '3 mois', en: '3 months' }, price: 2000 },
          { id: 'm6', label: { fr: '6 mois', en: '6 months' }, price: 3600 },
          { id: 'm12', label: { fr: '12 mois', en: '12 months' }, price: 6000 },
        ],
      },
    ],
  },
  web: {
    labelKey: 'web',
    from: 1500,
    questions: [
      {
        id: 'type',
        multi: false,
        title: { fr: 'Type de site', en: 'Site type' },
        options: [
          { id: 'showcase', label: { fr: 'Site vitrine', en: 'Showcase website' }, price: 1500 },
          { id: 'blog', label: { fr: 'Site avec blog', en: 'Website with blog' }, price: 2500 },
          { id: 'shop', label: { fr: 'Boutique en ligne', en: 'Online store' }, price: 4500 },
          { id: 'app', label: { fr: 'Application web sur mesure', en: 'Custom web application' }, price: 8000 },
        ],
      },
      {
        id: 'pages',
        multi: false,
        title: { fr: 'Nombre de pages', en: 'Number of pages' },
        options: [
          { id: 'p5', label: { fr: '1 à 5 pages', en: '1 to 5 pages' }, price: 0, included: true },
          { id: 'p10', label: { fr: '6 à 10 pages', en: '6 to 10 pages' }, price: 800 },
          { id: 'p20', label: { fr: '11 à 20 pages', en: '11 to 20 pages' }, price: 1800 },
          { id: 'p21', label: { fr: 'Plus de 20 pages', en: 'More than 20 pages' }, price: 3500 },
        ],
      },
      {
        id: 'features',
        multi: true,
        title: { fr: 'Fonctionnalités', en: 'Features' },
        options: [
          { id: 'cms', label: { fr: 'CMS (gestion de contenu)', en: 'CMS (content management)' }, price: 400 },
          { id: 'i18n', label: { fr: 'Multilingue', en: 'Multilingual' }, price: 600 },
          { id: 'seo', label: { fr: 'SEO avancé', en: 'Advanced SEO' }, price: 500 },
          { id: 'booking', label: { fr: 'Réservation en ligne', en: 'Online booking' }, price: 700 },
          { id: 'members', label: { fr: 'Espace membres', en: 'Member area' }, price: 800 },
        ],
      },
    ],
  },
  apps: {
    labelKey: 'apps',
    from: 5000,
    questions: [
      {
        id: 'platform',
        multi: false,
        title: { fr: 'Plateforme cible', en: 'Target platform' },
        options: [
          { id: 'ios', label: { fr: 'iOS uniquement', en: 'iOS only' }, price: 5000 },
          { id: 'android', label: { fr: 'Android uniquement', en: 'Android only' }, price: 5000 },
          { id: 'both', label: { fr: 'iOS et Android', en: 'iOS and Android' }, price: 8000 },
          { id: 'rn', label: { fr: 'Cross-platform (React Native)', en: 'Cross-platform (React Native)' }, price: 7000 },
        ],
      },
      {
        id: 'complexity',
        multi: false,
        title: { fr: 'Complexité', en: 'Complexity' },
        options: [
          { id: 'simple', label: { fr: 'Simple (5-8 écrans)', en: 'Simple (5-8 screens)' }, price: 0, included: true },
          { id: 'medium', label: { fr: 'Moyenne (9-15 écrans)', en: 'Medium (9-15 screens)' }, price: 4000 },
          { id: 'complex', label: { fr: 'Complexe (16+ écrans)', en: 'Complex (16+ screens)' }, price: 9000 },
        ],
      },
      {
        id: 'features',
        multi: true,
        title: { fr: 'Fonctionnalités', en: 'Features' },
        options: [
          { id: 'auth', label: { fr: 'Authentification utilisateurs', en: 'User authentication' }, price: 800 },
          { id: 'pay', label: { fr: 'Paiements in-app', en: 'In-app payments' }, price: 1200 },
          { id: 'push', label: { fr: 'Notifications push', en: 'Push notifications' }, price: 600 },
          { id: 'offline', label: { fr: 'Mode hors-ligne', en: 'Offline mode' }, price: 900 },
          { id: 'api', label: { fr: 'API / backend sur mesure', en: 'Custom API / backend' }, price: 2500 },
        ],
      },
    ],
  },
  drone: {
    labelKey: 'drone',
    from: 400,
    questions: [
      {
        id: 'type',
        multi: false,
        title: { fr: 'Type de service', en: 'Service type' },
        options: [
          { id: 'photo', label: { fr: 'Photographie aérienne', en: 'Aerial photography' }, price: 400 },
          { id: 'video', label: { fr: 'Vidéographie aérienne', en: 'Aerial videography' }, price: 800 },
          { id: 'inspect', label: { fr: 'Inspection', en: 'Inspection' }, price: 600 },
          { id: 'map', label: { fr: 'Cartographie 3D', en: '3D mapping' }, price: 1200 },
        ],
      },
      {
        id: 'duration',
        multi: false,
        title: { fr: 'Durée sur place', en: 'On-site duration' },
        options: [
          { id: 'half', label: { fr: 'Demi-journée', en: 'Half day' }, price: 0, included: true },
          { id: 'full', label: { fr: 'Journée complète', en: 'Full day' }, price: 400 },
          { id: 'multi', label: { fr: 'Plusieurs jours', en: 'Multiple days' }, price: 1200 },
        ],
      },
      {
        id: 'deliverables',
        multi: true,
        title: { fr: 'Livrables', en: 'Deliverables' },
        options: [
          { id: 'raw', label: { fr: 'Fichiers bruts', en: 'Raw files' }, price: 0, included: true },
          { id: 'edit', label: { fr: 'Montage / retouche', en: 'Editing / retouching' }, price: 300 },
          { id: 'uhd', label: { fr: 'Livraison 4K', en: '4K delivery' }, price: 200 },
          { id: 'rush', label: { fr: 'Livraison express (48h)', en: 'Rush delivery (48h)' }, price: 250 },
        ],
      },
    ],
  },
}
